output_dir: ~/experiment_result/

dataset:
  class: Indecommerce
  num_rows: 10000
  root: ~/processed_dataset/
  version: v1
  csv_file_path: ~/stage-gnn/link_prediction/data/ 
  train_categories: [computers.desktop, appliances.kitchen.refrigerators, furniture.bedroom.bed, electronics.smartphone, apparel.shoes]
  test_categories: [hm]
  # all available categories under E-commerce dataset: computers.desktop, appliances.kitchen.refrigerators, furniture.bedroom.bed, electronics.smartphone, apparel.shoes
  # all available categories under HM dataset: hm (does not work with feature_method=price since hm dataset does not contain price information)

model:
  class: NBFNet
  input_dim: 256
  hidden_dims: [256, 256, 256, 256, 256, 256]

  # choose one of the following feature methods
  # ["stage", "llm", "structural", "normalized", "raw", "gaussian", "price"]
  feature_method: stage

  # if chosen "stage" as feature_method, modify the following parameters as needed
  # otherwise, please ignore them
  edge_embed_dim: 256 
  edge_embed_num_layers: 1 
  edge_model: GINEConv
  use_p_value: True

# we use the same following parameters as in the original NBFNet paper
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no

task:
  num_negative: 64
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: [0]
  batch_size: 32
  num_epoch: 30
  log_interval: 100
